name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Pytest
      run: |
        
        pytest mydjangoproject/mydjangoapp/tests/test_models.py
    - name: Run Mutations
      run: |
        mutmut run --paths-to-mutate=mydjangoproject/mydjangoapp/tests/test_models.py  --tests-dir=mydjangoproject/mydjangoapp/tests/test_models.py
    - name: Run Performance Eval
      run: |
        pytest --benchmark-skip mydjangoproject/mydjangoapp/tests/test_models.py
        
